/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is normally generated by Next.js. It is committed here so the
// scaffold is self-describing before the first local `next dev` run.
