pub(super) const PROPOSAL_TEMPLATE_FILES: &[(&str, &str)] = &[
    (
        ".mdp/cards/bid-no-bid-rules.yaml",
        include_str!("../../../plugin/assets/templates/proposal/.mdp/cards/bid-no-bid-rules.yaml"),
    ),
    (
        ".mdp/cards/compliance-boundaries.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/cards/compliance-boundaries.yaml"
        ),
    ),
    (
        ".mdp/cards/evaluation-criteria.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/cards/evaluation-criteria.yaml"
        ),
    ),
    (
        ".mdp/cards/gaps.yaml",
        include_str!("../../../plugin/assets/templates/proposal/.mdp/cards/gaps.yaml"),
    ),
    (
        ".mdp/cards/opportunity-context.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/cards/opportunity-context.yaml"
        ),
    ),
    (
        ".mdp/cards/proof-library.yaml",
        include_str!("../../../plugin/assets/templates/proposal/.mdp/cards/proof-library.yaml"),
    ),
    (
        ".mdp/cards/proposal-boundaries.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/cards/proposal-boundaries.yaml"
        ),
    ),
    (
        ".mdp/cards/proposal-output-rules.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/cards/proposal-output-rules.yaml"
        ),
    ),
    (
        ".mdp/cards/proposal-roles.yaml",
        include_str!("../../../plugin/assets/templates/proposal/.mdp/cards/proposal-roles.yaml"),
    ),
    (
        ".mdp/cards/requirement-signals.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/cards/requirement-signals.yaml"
        ),
    ),
    (
        ".mdp/cards/requirements-matrix.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/cards/requirements-matrix.yaml"
        ),
    ),
    (
        ".mdp/cards/review-gates.yaml",
        include_str!("../../../plugin/assets/templates/proposal/.mdp/cards/review-gates.yaml"),
    ),
    (
        ".mdp/cards/review-outputs.yaml",
        include_str!("../../../plugin/assets/templates/proposal/.mdp/cards/review-outputs.yaml"),
    ),
    (
        ".mdp/evals/bid-no-bid-route.yaml",
        include_str!("../../../plugin/assets/templates/proposal/.mdp/evals/bid-no-bid-route.yaml"),
    ),
    (
        ".mdp/evals/compliance-route.yaml",
        include_str!("../../../plugin/assets/templates/proposal/.mdp/evals/compliance-route.yaml"),
    ),
    (
        ".mdp/evals/compliance-unsupported-claim.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/compliance-unsupported-claim.yaml"
        ),
    ),
    (
        ".mdp/evals/fit-insufficient-context.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/fit-insufficient-context.yaml"
        ),
    ),
    (
        ".mdp/evals/fit-policy-bypass-disqualified.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/fit-policy-bypass-disqualified.yaml"
        ),
    ),
    (
        ".mdp/evals/invented-proof-guardrail.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/invented-proof-guardrail.yaml"
        ),
    ),
    (
        ".mdp/evals/normalize-opportunity-insufficient-context.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/normalize-opportunity-insufficient-context.yaml"
        ),
    ),
    (
        ".mdp/evals/normalize-opportunity-invalid-source-kind.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/normalize-opportunity-invalid-source-kind.yaml"
        ),
    ),
    (
        ".mdp/evals/normalize-opportunity-missing-required-attribute.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/normalize-opportunity-missing-required-attribute.yaml"
        ),
    ),
    (
        ".mdp/evals/normalize-opportunity-missing-required-signal.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/normalize-opportunity-missing-required-signal.yaml"
        ),
    ),
    (
        ".mdp/evals/normalize-opportunity-output.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/normalize-opportunity-output.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-claim-source-ref-missing.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/proof-output-claim-source-ref-missing.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-connective-text.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/proof-output-connective-text.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-connective-too-long.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/proof-output-connective-too-long.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-fake-id.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/proof-output-fake-id.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-gap-only-safe.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/proof-output-gap-only-safe.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-malformed-artifact.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/proof-output-malformed-artifact.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-min-segments-violation.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/proof-output-min-segments-violation.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-missing-binding.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/proof-output-missing-binding.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-missing-required-segment.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/proof-output-missing-required-segment.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-unsupported-claim.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/proof-output-unsupported-claim.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-valid-binding.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/proof-output-valid-binding.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-review-route.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/evals/proof-review-route.yaml"
        ),
    ),
    (
        ".mdp/evals/proposal-gaps.yaml",
        include_str!("../../../plugin/assets/templates/proposal/.mdp/evals/proposal-gaps.yaml"),
    ),
    (
        ".mdp/evals/red-team-route.yaml",
        include_str!("../../../plugin/assets/templates/proposal/.mdp/evals/red-team-route.yaml"),
    ),
    (
        ".mdp/manifest.yaml",
        include_str!("../../../plugin/assets/templates/proposal/.mdp/manifest.yaml"),
    ),
    (
        ".mdp/prompts/normalize-opportunity.yaml",
        include_str!(
            "../../../plugin/assets/templates/proposal/.mdp/prompts/normalize-opportunity.yaml"
        ),
    ),
    (
        ".mdp/sources.yaml",
        include_str!("../../../plugin/assets/templates/proposal/.mdp/sources.yaml"),
    ),
    (
        "examples/proof-output/claim-source-ref-missing.json",
        include_str!(
            "../../../plugin/assets/templates/proposal/examples/proof-output/claim-source-ref-missing.json"
        ),
    ),
    (
        "examples/proof-output/connective-text.json",
        include_str!(
            "../../../plugin/assets/templates/proposal/examples/proof-output/connective-text.json"
        ),
    ),
    (
        "examples/proof-output/connective-too-long.json",
        include_str!(
            "../../../plugin/assets/templates/proposal/examples/proof-output/connective-too-long.json"
        ),
    ),
    (
        "examples/proof-output/fake-id.json",
        include_str!(
            "../../../plugin/assets/templates/proposal/examples/proof-output/fake-id.json"
        ),
    ),
    (
        "examples/proof-output/gap-only-safe.json",
        include_str!(
            "../../../plugin/assets/templates/proposal/examples/proof-output/gap-only-safe.json"
        ),
    ),
    (
        "examples/proof-output/malformed-artifact.json",
        include_str!(
            "../../../plugin/assets/templates/proposal/examples/proof-output/malformed-artifact.json"
        ),
    ),
    (
        "examples/proof-output/min-segments-violation.json",
        include_str!(
            "../../../plugin/assets/templates/proposal/examples/proof-output/min-segments-violation.json"
        ),
    ),
    (
        "examples/proof-output/missing-binding.json",
        include_str!(
            "../../../plugin/assets/templates/proposal/examples/proof-output/missing-binding.json"
        ),
    ),
    (
        "examples/proof-output/missing-required-segment.json",
        include_str!(
            "../../../plugin/assets/templates/proposal/examples/proof-output/missing-required-segment.json"
        ),
    ),
    (
        "examples/proof-output/unsupported-claim.json",
        include_str!(
            "../../../plugin/assets/templates/proposal/examples/proof-output/unsupported-claim.json"
        ),
    ),
    (
        "examples/proof-output/valid-binding.json",
        include_str!(
            "../../../plugin/assets/templates/proposal/examples/proof-output/valid-binding.json"
        ),
    ),
];

pub(super) const RECRUITING_TEMPLATE_FILES: &[(&str, &str)] = &[
    (
        ".mdp/cards/candidate-evidence.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/cards/candidate-evidence.yaml"
        ),
    ),
    (
        ".mdp/cards/evidence-standards.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/cards/evidence-standards.yaml"
        ),
    ),
    (
        ".mdp/cards/gaps.yaml",
        include_str!("../../../plugin/assets/templates/recruiting/.mdp/cards/gaps.yaml"),
    ),
    (
        ".mdp/cards/recruiting-boundaries.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/cards/recruiting-boundaries.yaml"
        ),
    ),
    (
        ".mdp/cards/recruiting-output-rules.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/cards/recruiting-output-rules.yaml"
        ),
    ),
    (
        ".mdp/cards/recruiting-roles.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/cards/recruiting-roles.yaml"
        ),
    ),
    (
        ".mdp/cards/review-criteria.yaml",
        include_str!("../../../plugin/assets/templates/recruiting/.mdp/cards/review-criteria.yaml"),
    ),
    (
        ".mdp/cards/review-gates.yaml",
        include_str!("../../../plugin/assets/templates/recruiting/.mdp/cards/review-gates.yaml"),
    ),
    (
        ".mdp/cards/review-outputs.yaml",
        include_str!("../../../plugin/assets/templates/recruiting/.mdp/cards/review-outputs.yaml"),
    ),
    (
        ".mdp/cards/role-context.yaml",
        include_str!("../../../plugin/assets/templates/recruiting/.mdp/cards/role-context.yaml"),
    ),
    (
        ".mdp/cards/role-requirements.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/cards/role-requirements.yaml"
        ),
    ),
    (
        ".mdp/evals/autonomous-outcome-refusal.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/autonomous-outcome-refusal.yaml"
        ),
    ),
    (
        ".mdp/evals/candidate-evidence-route.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/candidate-evidence-route.yaml"
        ),
    ),
    (
        ".mdp/evals/create-pack-route.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/create-pack-route.yaml"
        ),
    ),
    (
        ".mdp/evals/interview-brief-route.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/interview-brief-route.yaml"
        ),
    ),
    (
        ".mdp/evals/invented-credentials-unsafe.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/invented-credentials-unsafe.yaml"
        ),
    ),
    (
        ".mdp/evals/normalize-recruiting-context-insufficient.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/normalize-recruiting-context-insufficient.yaml"
        ),
    ),
    (
        ".mdp/evals/normalize-recruiting-context-invalid-decision.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/normalize-recruiting-context-invalid-decision.yaml"
        ),
    ),
    (
        ".mdp/evals/normalize-recruiting-context-missing-source-safety.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/normalize-recruiting-context-missing-source-safety.yaml"
        ),
    ),
    (
        ".mdp/evals/normalize-recruiting-context-missing-source.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/normalize-recruiting-context-missing-source.yaml"
        ),
    ),
    (
        ".mdp/evals/normalize-recruiting-context-output.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/normalize-recruiting-context-output.yaml"
        ),
    ),
    (
        ".mdp/evals/pack-validation-route.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/pack-validation-route.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-fake-id.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/proof-output-fake-id.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-missing-binding.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/proof-output-missing-binding.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-missing-gap.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/proof-output-missing-gap.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-unsupported-claim.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/proof-output-unsupported-claim.yaml"
        ),
    ),
    (
        ".mdp/evals/proof-output-valid-binding.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/proof-output-valid-binding.yaml"
        ),
    ),
    (
        ".mdp/evals/protected-proxy-refusal.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/protected-proxy-refusal.yaml"
        ),
    ),
    (
        ".mdp/evals/recruiting-gaps.yaml",
        include_str!("../../../plugin/assets/templates/recruiting/.mdp/evals/recruiting-gaps.yaml"),
    ),
    (
        ".mdp/evals/recruiting-insufficient-context.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/recruiting-insufficient-context.yaml"
        ),
    ),
    (
        ".mdp/evals/role-requirements-route.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/role-requirements-route.yaml"
        ),
    ),
    (
        ".mdp/evals/scorecard-gap-route.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/scorecard-gap-route.yaml"
        ),
    ),
    (
        ".mdp/evals/unverified-source-refusal.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/evals/unverified-source-refusal.yaml"
        ),
    ),
    (
        ".mdp/manifest.yaml",
        include_str!("../../../plugin/assets/templates/recruiting/.mdp/manifest.yaml"),
    ),
    (
        ".mdp/prompts/normalize-recruiting-context.yaml",
        include_str!(
            "../../../plugin/assets/templates/recruiting/.mdp/prompts/normalize-recruiting-context.yaml"
        ),
    ),
    (
        ".mdp/sources.yaml",
        include_str!("../../../plugin/assets/templates/recruiting/.mdp/sources.yaml"),
    ),
    (
        "examples/proof-output/fake-id.json",
        include_str!(
            "../../../plugin/assets/templates/recruiting/examples/proof-output/fake-id.json"
        ),
    ),
    (
        "examples/proof-output/missing-binding.json",
        include_str!(
            "../../../plugin/assets/templates/recruiting/examples/proof-output/missing-binding.json"
        ),
    ),
    (
        "examples/proof-output/missing-gap.json",
        include_str!(
            "../../../plugin/assets/templates/recruiting/examples/proof-output/missing-gap.json"
        ),
    ),
    (
        "examples/proof-output/unsupported-claim.json",
        include_str!(
            "../../../plugin/assets/templates/recruiting/examples/proof-output/unsupported-claim.json"
        ),
    ),
    (
        "examples/proof-output/valid-binding.json",
        include_str!(
            "../../../plugin/assets/templates/recruiting/examples/proof-output/valid-binding.json"
        ),
    ),
];
